name: reddit-app
version: git
version-script: "python -c \"from reddit-app.constants import VERSION; print(VERSION)\""
summary: Keep your application settings in sync
description: |
  Back ups your application settings in a safe directory (e.g. Dropbox).
  Syncs your application settings among all your workstations.
  Restores your configuration on any fresh install in one command line.

grade: stable
confinement: classic

apps:
  reddit-app:
    command: bin/reddit-app

parts:
  reddit-app:
    plugin: python
    python-version: python3
    source: .